export const brand = {
  primary: "var(--ui-primary, #150578)",
  primaryHover: "var(--ui-primary-hover, #1f0a9e)",
  onPrimary: "var(--ui-on-primary, #ffffff)",
  accent: "var(--ui-accent, #3943B7)",
  border: "var(--ui-border, #d7deea)",
  text: "var(--ui-text, #0f172a)",
  muted: "var(--ui-muted, #64748b)",
  danger: "var(--ui-danger, #b42318)",
  dangerBg: "var(--ui-danger-bg, #fef3f2)",
  dangerBorder: "var(--ui-danger-border, #fecdca)",
  surface: "var(--ui-surface, #ffffff)",
  surfaceMuted: "var(--ui-surface-muted, #f8fafc)",
  success: "var(--ui-success, #027a48)",
  successBg: "var(--ui-success-bg, #ecfdf3)",
  successBorder: "var(--ui-success-border, #abefc6)",
  warning: "var(--ui-warning, #b54708)",
  warningBg: "var(--ui-warning-bg, #fffaeb)",
  warningBorder: "var(--ui-warning-border, #fedf89)",
  infoBg: "var(--ui-info-bg, #eff8ff)",
  infoBorder: "var(--ui-info-border, #b2ddff)",
  iconBg: "var(--ui-icon-bg, rgba(21, 5, 120, 0.08))",
  shadow: "var(--ui-shadow, 0 10px 30px rgba(15, 23, 42, 0.06))",
  skeletonFrom: "var(--ui-skeleton-from, #e2e8f0)",
  skeletonVia: "var(--ui-skeleton-via, #f1f5f9)",
} as const;
